# Generated by Django 5.2.8 on 2025-12-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='setor',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
